global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:5000"]

  - job_name: "pedidos-service"
    static_configs:
      - targets: ["pedidos-service:5001"]

  - job_name: "pagamentos-service"
    static_configs:
      - targets: ["pagamentos-service:5002"]

  - job_name: "estoque-service"
    static_configs:
      - targets: ["estoque-service:5003"]
