apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pedidos-veloz
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  ESTOQUE_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/estoque_db
  PAGAMENTOS_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pagamentos_db
  PEDIDOS_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pedidos_db
